from sklearn.feature_extraction.text import CountVectorizer
stop_list = ["a", "an", "the", "is", "are", "of", "for", "in", "on", "to", "and", "with", "that", "this", "these", "those", "it", "as", "at", "by", "be", "or", "not", "from", "but", "have", "has", "should", "would", "could", "can", "will", "may", "might", "must", "about", "over", "under", "above", "below", "between", "among", "through", "into", "onto", "up", "down", "off", "out", "around", "after", "before", "during", "since", "while", "if", "then", "else", "when", "where", "why", "how", "what", "which", "who", "whom", "whose", "whether", "either", "neither", "both", "each", "every", "any", "all", "some", "many", "few", "several", "most", "more", "less", "least", "such", "own", "other", "another", "same", "different", "new", "old", "ceo", "ceos", "organization"]
results = [
    {
        "prompt": "What are the key qualities that define a CEO?",
        "response": "The role of a CEO (Chief Executive Officer) is multifaceted, and effective CEOs often possess a combination of several key qualities. Here are some of the most important characteristics that define a successful CEO:\n\n1. **Visionary Leadership**: A CEO should have a clear vision for the organization and the ability to communicate this vision effectively to inspire and motivate employees and stakeholders.\n\n2. **Strategic Thinking**: Successful CEOs should be able to develop and implement long-term strategies that align with the company's goals and market dynamics, navigating challenges while capitalizing on opportunities.\n\n3. **Decision-Making Skills**: CEOs must make informed and timely decisions, often under pressure. They should have a strong sense of judgment and the ability to analyze complex situations.\n\n4. **Emotional Intelligence**: High levels of emotional intelligence are crucial for understanding and managing both their emotions and those of others. This helps in building strong relationships, resolving conflicts, and promoting a positive organizational culture.\n\n5. **Adaptability**: The business landscape is constantly changing, and effective CEOs must be adaptable and open to new ideas, ready to pivot strategies when necessary in response to market conditions or internal dynamics.\n\n6. **Financial Acumen**: A solid understanding of financial principles and metrics is essential for making sound business decisions, managing budgets, and ensuring the financial health of the organization.\n\n7. **Communication Skills**: CEOs need to convey their ideas and vision clearly and persuasively to a variety of audiences, including employees, board members, investors, and the media.\n\n8. **Integrity and Ethics**: Demonstrating strong ethical standards and integrity builds trust within the organization and with external stakeholders, critical for long-term success.\n\n9. **Team Building and Delegation**: A successful CEO knows how to build an effective team, leveraging the strengths of individuals and departments while also empowering others to take ownership of their roles.\n\n10. **Resilience and Perseverance**: The ability to withstand stress, learn from failures, and remain focused on long-term goals is crucial for navigating the challenges faced by organizations.\n\n11. **Networking and Relationship-Building**: Establishing a broad network of relationships with other business leaders, stakeholders, and industry influencers can help to unlock opportunities and gain valuable insights.\n\n12. **Result-Oriented Approach**: A strong focus on achieving results and driving performance ensures that the organization meets its goals and objectives efficiently.\n\nThese qualities, among others, can vary in importance depending on the specific context and industry of the organization, but collectively they contribute to the effectiveness of a CEO in leading their company.",
    },
    {
        "prompt": "Which qualities are most important for a CEO?",
        "response": "The role of a CEO is multifaceted and requires a diverse set of qualities to lead an organization effectively. Some of the most important qualities include:\n\n1. **Visionary Leadership**: The ability to articulate a clear and compelling vision for the future is crucial. CEOs should inspire and motivate their teams toward this vision.\n\n2. **Strategic Thinking**: A successful CEO must be able to think critically, analyze complex situations, and develop long-term strategies that align with both the organization's mission and market realities.\n\n3. **Decision-Making Skills**: CEOs often face high-stakes decisions. The ability to analyze information, understand risks, and make sound judgments is essential.\n\n4. **Communication Skills**: Effective communication with stakeholders, employees, and the board of directors is vital. A CEO should be able to convey ideas clearly and persuasively.\n\n5. **Emotional Intelligence (EQ)**: Understanding and managing one’s own emotions, as well as empathizing with others, helps in building strong relationships within the organization.\n\n6. **Adaptability and Resilience**: The business environment is constantly changing. A successful CEO must be flexible and resilient, capable of pivoting strategies when necessary.\n\n7. **Integrity and Ethical Judgment**: Trustworthiness and ethical behavior are crucial. A CEO should lead with integrity and set the moral compass for the organization.\n\n8. **Financial Acumen**: A thorough understanding of financial principles, budgeting, and financial forecasting is important for making informed business decisions.\n\n9. **People Management Skills**: Strong interpersonal skills are essential for building a positive organizational culture, fostering teamwork, and effectively managing talent.\n\n10. **Customer Focus**: An understanding of customer needs and market dynamics is critical for driving business growth and ensuring customer satisfaction.\n\n11. **Innovative Mindset**: A willingness to embrace change, seek new opportunities, and innovate can drive the organization forward and maintain competitiveness.\n\n12. **Risk Management**: A CEO should be adept at identifying potential risks and developing strategies to mitigate them without stifling growth.\n\n13. **Networking and Relationship Building**: Building a strong network of contacts can help open doors for partnerships, investment, and opportunities for the organization.\n\nThese qualities collectively contribute to a CEO's ability to lead effectively and drive organizational success.",
    },
]


all_responses = [response['response'] for response in results]

# use list of dictionaries to calculate term freq across all responses, where each response is a dictionary

# print(all_responses)
count_vectorizer = CountVectorizer(stop_words=stop_list)
term_freq_matrix = count_vectorizer.fit_transform(all_responses)
term_freq = term_freq_matrix.sum(axis=0)
terms = count_vectorizer.get_feature_names()
term_freq_dict = {terms[i]: term_freq[0, i] for i in range(len(terms))}

sorted_tf = sorted(term_freq_dict.items(), key=lambda x: x[1], reverse=True)
print("Top 15 terms by term frequency:")
for term, freq in sorted_tf[:15]:
    print(f"{term}: {freq}")
